# Site Settings
title                    : "Wine Country Inn"
title_separator          : "|"
name                     : "Wine Country Inn"
description              : "Wine Country Inn"
url                      : # the base hostname & protocol for your site e.g. "https://www.traveltripper.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : https://github.com/TravelTripperWeb-Sites/wine-country-inn # GitHub username/repo-name e.g. "TravelTripperWeb/bedrock"

# Language Settings
default_lang             : 'en'
languages                : ['en']

# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - Makefile
  - media.json
  - models.json
  - node_modules
  - old_media.json
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - sitemap.json
  - tmp
keep_files:
  - .git
  - assets
rsync_copy:
- _assets
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
    load_paths:
        - _sass
    style: compressed

# Outputting
permalink: pretty
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

data_paginate: 
    per_page: 5
    data: 'blog'
    path: 'blog/page:num'
    pagination_template: 'blog/index.html'
    sort_field: 'date'

page_gen: # 
  - data: 'accommodations'
    template: 'accommodation-details'
    dir: 'accommodations'
  - data: 'offers'
    template: 'offer-details'
    dir: 'offers'
  - data: 'blog'
    template: 'blog-details'
    dir: 'blog'
  # - data: 'category'
  #   template: 'category-list'
  #   dir: 'blog/category'